# Generated by Django 5.2.3 on 2025-06-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=20, unique=True)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_dob', models.DateField()),
                ('cust_gender', models.CharField(max_length=10)),
                ('cust_phone', models.CharField(max_length=15)),
                ('cust_email', models.EmailField(max_length=50)),
                ('cust_address', models.CharField(max_length=200)),
                ('cust_blood_group', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('emp_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('present_address', models.CharField(max_length=200)),
                ('emp_position', models.CharField(max_length=300)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('emp_photo', models.ImageField(null=True, upload_to='employee_photos/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=20, unique=True)),
                ('medicine_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('unit_type', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(max_length=20, unique=True)),
                ('invoice_no', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('payment_status', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('medicine_categories', models.CharField(max_length=50)),
                ('lience_number', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('payment_month', models.CharField(max_length=7)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.employee', to_field='emp_id')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_item', models.CharField(max_length=20, unique=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantituy', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.medicine', to_field='medicine_id')),
                ('purchhase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.purchase', to_field='purchase_id')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=20)),
                ('order_status', models.CharField(max_length=20)),
                ('delivery_date', models.DateField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.customer', to_field='cust_id')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_item_id', models.CharField(max_length=50, unique=True)),
                ('batch_no', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('mfg_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.medicine', to_field='medicine_id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('current_qty', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.medicine', to_field='medicine_id')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_private.supplier', to_field='supplier_id'),
        ),
    ]
