# Generated by Django 5.2.3 on 2025-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total_amount',
            new_name='final_amount',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='payment_status',
            new_name='payment_mode',
        ),
        migrations.AddField(
            model_name='purchase',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_item',
            field=models.CharField(max_length=20),
        ),
    ]
