# Generated by Django 5.2.3 on 2025-07-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0002_rename_total_amount_purchase_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
