# Generated by Django 5.2.3 on 2025-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0003_purchaseitem_sellingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='stock',
            name='medicine_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
