# Generated by Django 5.2.3 on 2025-07-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0004_remove_stock_last_updated_remove_stock_stock_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
