# Generated by Django 5.2.3 on 2025-07-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0005_remove_sales_delivery_date_saleitem_line_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='selling_pricee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
