# Generated by Django 5.2.3 on 2025-07-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0006_saleitem_selling_pricee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='selling_pricee',
            new_name='selling_price',
        ),
    ]
