# Generated by Django 5.2.3 on 2025-07-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0007_rename_selling_pricee_saleitem_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
