# Generated by Django 5.2.3 on 2025-07-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0008_remove_saleitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='mfg_date',
        ),
    ]
