# Generated by Django 5.2.3 on 2025-07-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0009_remove_saleitem_expiry_date_remove_saleitem_mfg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_item_id',
        ),
    ]
