# Generated by Django 5.2.3 on 2025-07-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_private', '0010_remove_saleitem_sale_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='autogenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supid', models.CharField(default=0, max_length=50)),
                ('pid', models.CharField(default=0, max_length=50)),
                ('cid', models.CharField(default=0, max_length=50)),
                ('empid', models.CharField(default=0, max_length=50)),
                ('oid', models.CharField(default=0, max_length=50)),
                ('mid', models.CharField(default=0, max_length=50)),
                ('payid', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
